# Usar uma imagem base com Python 3.12
FROM python:3.12-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo .py para o container
COPY main.py .

# Definir o comando para executar o arquivo Python
CMD ["python", "main.py"]
